# Generated by Django 6.1 on 2026-08-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Reyting')),
                ('work_start_time', models.TimeField(default='09:00', verbose_name='Ish boshlanish vaqti')),
                ('work_end_time', models.TimeField(default='18:00', verbose_name='Ish tugash vaqti')),
                ('is_available', models.BooleanField(default=True, verbose_name='Hozir band emas')),
                ('services', models.ManyToManyField(blank=True, related_name='barbers', to='services.service', verbose_name="Ko'rsatadigan xizmatlar")),
            ],
            options={
                'verbose_name': 'Usta profili',
                'verbose_name_plural': 'Ustalar profillari',
                'ordering': ['-rating'],
            },
        ),
    ]
