services:
  - type: web
    name: royal-barber
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: TELEGRAM_BOT_TOKEN
        value: "8937609200:AAFBw4nfLHSJetvKyqZSKa6NPoTsh3Iww4k"
      - key: TELEGRAM_BOT_USERNAME
        value: "royalbarber_bot"
      - key: DJANGO_SUPERUSER_PHONE
        value: "+998000000000"
      - key: DJANGO_SUPERUSER_NAME
        value: "Admin"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "RoyalAdmin2024!"
