# Generated by Django 5.2.17 on 2026-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=10)),
                ('password_hash', models.CharField(blank=True, max_length=256)),
                ('code', models.CharField(max_length=10, verbose_name='OTP kod')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Telegram OTP',
                'verbose_name_plural': 'Telegram OTP lar',
            },
        ),
    ]
