# Generated by Django 5.2.17 on 2026-08-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ★'), (2, '2 ★★'), (3, '3 ★★★'), (4, '4 ★★★★'), (5, '5 ★★★★★')], null=True, verbose_name='Mijoz bahosi (1-5)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='review',
            field=models.TextField(blank=True, verbose_name='Mijoz sharhi'),
        ),
    ]
